//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Likes = new HashSet<Likes>();
        }
        [DisplayName("—ﬁ„ «·ﬂ «»  ")]

        public int Book_Id { get; set; }
        [DisplayName("  «”„ «·ﬂ «» ")]

        public string Book_Name { get; set; }
        [DisplayName("«”„ «·ﬂ« »  ")]

        public string Book_Author { get; set; }
        [DisplayName("  «—ÌŒ «·‰‘— ")]

        public string Publish_Date { get; set; }
        [DisplayName("  —ﬁ„ «·ﬁ”„")]

        public int Dep_Id { get; set; }
        [DisplayName("  —«»ÿ  Õ„Ì· «·ﬂ «»")]

        public string Book_link { get; set; }
        [DisplayName("  ’Ê—… «·ﬂ «»")]

        public string Book_Pic { get; set; }
        [DisplayName(" ·„Õ… ⁄‰ «·ﬂ «» ")]

        public string Book_Details { get; set; }
        [DisplayName("  ⁄œœ ’›Õ«  «·ﬂ «»")]

        public int Book_Pages { get; set; }
        public byte[] img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Likes> Likes { get; set; }
        public virtual Department Department { get; set; }
    }
}
