//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public int Like_Id { get; set; }
        public int Book_id { get; set; }
        public int User_id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Users Users { get; set; }
    }
}
