//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Likes = new HashSet<Likes>();
        }
        [DisplayName("—ﬁ„ «·„” Œœ„  ")]

        public int User_Id { get; set; }
        [DisplayName("«”„ «·„” Œœ„  ")]
        [Required]
        public string User_Name { get; set; }
        [DisplayName("  ﬂ·„… «·„—Ê—")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [DisplayName("   «—ÌŒ «·„Ì·«œ")]

        public Nullable<System.DateTime> Birthdate { get; set; }
        [DisplayName("  Õ«·… «·√œ„‰")]

        public Nullable<bool> isAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Likes> Likes { get; set; }
    }
}
